# Generated by Django 2.2.22 on 2021-05-07 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_config', '0003_name_unique_per_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='subnet',
            field=models.ForeignKey(
                blank=True,
                help_text='Subnet IP addresses used by VPN clients, if applicable',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OPENWISP_IPAM_SUBNET_MODEL,
                verbose_name='Subnet',
            ),
        ),
    ]
